#!/bin/bash
source /home/muf/.scripts/porkbun
#acme.sh --register-account -m strah.luna@gmail.com
acme.sh --issue --dns dns_porkbun -d muf.moe -d "*.muf.moe"
acme.sh --install-cert --ecc -d muf.moe \
  --cert-file /etc/nginx/ssl/muf.moe/cert \
  --key-file /etc/nginx/ssl/muf.moe/key \
  --fullchain-file /etc/nginx/ssl/muf.moe/fullchain \
  --reloadcmd "systemctl reload nginx.service"
