#! /bin/sh

if (( $# == 0 )); then
	>&2 echo "Missing base name"
	exit 1
elif (( $# == 1 )); then
	EXT="mkv"
else
	EXT=$2
fi
BASENAME=$1

ffmpeg -i "${BASENAME}a.${EXT}" -i "${BASENAME}b.${EXT}" \
       -filter_complex "[0:v] [0:a] [1:v] [1:a]
                        concat=n=2:v=1:a=1 [v] [a]" \
       -map "[v]" -map "[a]" "${BASENAME}.${EXT}"
