#!/bin/python
import xerox as cb
import re

def url2uri(s):
    return re.sub(r'^https://open.spotify.com/(.*)/([^\?]*)(\?si=.*)?',
                  r'spotify:\1:\2', s)
 

cb.copy(url2uri(cb.paste(xsel=True)), xsel=True)

